version: "3.9"
services:
  backend:
    container_name: ${APP_BACKEND_CONTAINER_NAME}
    build:
      context: ./backend
    volumes:
      - ./backend/app:/backend/app
    depends_on:
      - mysql
    ports:
      - ${APP_BACKEND_PORT}:8080
  frontend:
    container_name: ${APP_FRONTEND_CONTAINER_NAME}
    build:
      context: ./frontend
    volumes:
      - ./frontend/app:/frontend/app
      - ./frontend/nginx/log:/var/log/nginx
    ports:
      - ${APP_FRONTEND_PORT}:80
  mysql:
    image: mysql:latest
    container_name: ${DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
